name: Add issues/PRs to project

on:
  workflow_call

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          # Add to the primary project
          project-url: https://github.com/orgs/sendahug/projects/7
          github-token: ${{ secrets.ISSUES_PRS_PAT }}
